version: "3.3"
services:
  mobile_api_sendotp:
    image: dokerhub.tnmtm.in:5000/prodmobileapisendotp
    ports:
      - "9000:5000"
  mobile_api_validateOTP:
    image: dokerhub.tnmtm.in:5000/prodmobileapivalidateotp
    ports:
      - "9001:5000"
  mobile_api_resendOTP:
    image: dokerhub.tnmtm.in:5000/prodmobileapiresendotp
    ports:
      - "9002:5000"
  mobile_api_add_update_family_detail:
    image: dokerhub.tnmtm.in:5000/prodmobileapiaddupdatefamilydetail
    ports:
      - "9003:5000"
  mobile_api_get_block_list:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetblocklist
    ports:
      - "9004:5000"
  mobile_api_get_clinical_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetclinicaldata
    ports:
      - "9005:5000"
  mobile_api_get_district_list:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetdistrictlist
    ports:
      - "9006:5000"
  mobile_api_get_facility:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetfacility
    ports:
      - "9007:5000"
  mobile_api_get_family_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetfamilydata
    ports:
      - "9008:5000"
  mobile_api_get_family_member_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetfamilymemberdata
    ports:
      - "9009:5000"
  mobile_api_get_medical_history:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetmedicalhistory
    ports:
      - "9010:5000"
  mobile_api_get_screening_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetscreeningdata
    ports:
      - "9011:5000"
  mobile_api_get_search_family_details:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetsearchfamilydetails
    ports:
      - "9012:5000"
  mobile_api_get_village_list:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetvillagelist
    ports:
      - "9013:5000"
  mobile_api_get_village_street:
    image: dokerhub.tnmtm.in:5000prod/mobileapigetvillagestreet
    ports:
      - "9014:5000"
  mobile_api_health_history:
    image: dokerhub.tnmtm.in:5000/prodmobileapihealthhistory
    ports:
      - "9015:5000"
  mobile_api_health_screening:
    image: dokerhub.tnmtm.in:5000/prodmobileapihealthscreening
    ports:
      - "9016:5000"
  mobile_api_search:
    image: dokerhub.tnmtm.in:5000/prodmobileapisearch
    ports:
      - "9017:5000"
  mobile_api_upload:
    image: dokerhub.tnmtm.in:5000/prodmobileapiupload
    ports:
      - "9018:5000"
    volumes:
      - type: volume
        source: file_upload_volumes
        target: /Mobile_Api_Prod/mobile_api_upload/userImage
  phrlocker_api_v1:
    image: vigneshanbu92/phrlooker-api-prod-2:api2prod
    ports:
      - "9025:80"
  phrlocker_view_v1:
    image: vigneshanbu92/phrlocker_view_v1:phrlocker-view
    ports:
      - "9026:80"
  phrlocker_view_v2:
    image: vigneshanbu92/phrlocker_view_v2:ViewanbuRelease
    ports:
      - "9027:80"
volumes:
  file_upload_volumes:
