version: '3'
services:
  mobile_api_sendotp:
    image: tnphr/mobileapisendotp
    ports:
      - "9000:5000"
  mobile_api_validateOTP:
    image: tnphr/mobileapivalidateotp
    ports:
      - "9001:5000"
  mobile_api_resendOTP:
    image: tnphr/mobileapiresendotp
    ports:
      - "9002:5000"
  mobile_api_get_facility:
    image: tnphr/mobileapigetfacility
    ports:
      - "9003:5000"
  mobile_api_get_block_list:
    image: tnphr/mobileapigetblocklist
    ports:
      - "9004:5000"
  mobile_api_get_clinical_data:
    image: tnphr/mobileapigetclinicaldata
    ports:
      - "9005:5000"
  mobile_api_get_district_list:
    image: tnphr/mobileapigetdistrictlist
    ports:
      - "9006:5000"
  mobile_api_get_family_data:
    image: tnphr/mobileapigetfamilydata
    ports:
      - "9007:5000"
  mobile_api_get_village_street:
    image: tnphr/mobileapigetvillagestreet
    ports:
      - "9008:5000"
  mobile_api_get_village_list:
    image: tnphr/mobileapigetvillagelist
    ports:
      - "9009:5000"
  mobile_api_get_screening_data:
    image: tnphr/mobileapigetscreeningdata
    ports:
      - "9010:5000"
  mobile_api_get_search_family_details:
    image: tnphr/mobileapigetsearchfamilydetails
    ports:
      - "9011:5000"
  mobile_api_search:
    image: tnphr/mobileapisearch
    ports:
      - "9012:5000"
  mobile_api_get_family_member_data:
    image: tnphr/mobileapigetfamilymemberdata
    ports:
      - "9013:5000"
  mobile_api_get_medical_history:
    image: tnphr/mobileapigetmedicalhistory
    ports:
      - "9014:5000"
  mobile_api_add_update_family_detail:
    image: tnphr/mobileapiaddupdatefamilydetail
    ports:
      - "9015:5000"
  mobile_api_health_history:
    image: tnphr/mobileapihealthhistory
    ports:
      - "9016:5000"
  mobile_api_health_screening:
    image: tnphr/mobileapihealthscreening
    ports:
      - "9017:5000"
  mobile_api_upload:
    image: tnphr/mobileapiupload
    ports:
      - "9018:5000"
    volumes:
      - type: volume
        source: file_upload_volumes
        target: /Mobile_Api_Dev/mobile_api_upload/userImage
volumes:
  file_upload_volumes:
