version: '3.3'
services:
  mobileapisendotp:
    image: dokerhub.tnmtm.in:5000/prodmobileapisendotp
    ports:
      - "9000:80"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9000/api/mobile_api_sendotp/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_validateOTP:
    image: dokerhub.tnmtm.in:5000/prodmobileapivalidateotp
    ports:
      - "9001:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9001/api/mobile_api_validateOTP/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_resendOTP:
    image: dokerhub.tnmtm.in:5000/prodmobileapiresendotp
    ports:
      - "9002:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9002/api/mobile_api_resendOTP/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_facility:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetfacility
    ports:
      - "9003:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9003/api/mobile_api_get_facility/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_block_list:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetblocklist
    ports:
      - "9004:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9004/api/mobile_api_get_block_list/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_clinical_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetclinicaldata
    ports:
      - "9005:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9005/api/mobile_api_get_clinical_data/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_district_list:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetdistrictlist
    ports:
      - "9006:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9006/api/mobile_api_get_district_list/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_family_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetfamilydata
    ports:
      - "9007:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9007/api/mobile_api_get_family_data/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_village_street:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetvillagestreet
    ports:
      - "9008:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9008/api/mobile_api_get_village_street/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_village_list:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetvillagelist
    ports:
      - "9009:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9009/api/mobile_api_get_village_list/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_screening_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetscreeningdata
    ports:
      - "9010:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9010/api/mobile_api_get_screening_data/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_search_family_details:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetsearchfamilydetails
    ports:
      - "9011:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9011/api/mobile_api_get_search_family_details/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_search:
    image: dokerhub.tnmtm.in:5000/prodmobileapisearch
    ports:
      - "9012:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9012/api/mobile_api_search/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_family_member_data:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetfamilymemberdata
    ports:
      - "9013:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9013/api/mobile_api_get_family_member_data/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_get_medical_history:
    image: dokerhub.tnmtm.in:5000/prodmobileapigetmedicalhistory
    ports:
      - "9014:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9014/api/mobile_api_get_medical_history/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_add_update_family_detail:
    image: dokerhub.tnmtm.in:5000/prodmobileapiaddupdatefamilydetail
    ports:
      - "9015:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9015/api/mobile_api_add_update_family_detail/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_health_history:
    image: dokerhub.tnmtm.in:5000/prodmobileapihealthhistory
    ports:
      - "9016:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9016/api/mobile_api_health_history/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_health_screening:
    image: dokerhub.tnmtm.in:5000/prodmobileapihealthscreening
    ports:
      - "9017:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9017/api/mobile_api_health_screening/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  mobile_api_upload:
    image: dokerhub.tnmtm.in:5000/prodmobileapiupload
    ports:
      - "9018:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9018/api/mobile_api_upload/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
    volumes:
      - type: volume
        source: file_upload_volumes
        target: /Mobile_Api_Prod/mobile_api_upload/userImage
  mobile_api_refresh_token:
    image: dokerhub.tnmtm.in:5000/prodmobileapirefreshtoken
    ports:
      - "9019:5000"
    restart: always
    healthcheck:
      test: curl --fail http://10.236.220.92:9019/api/mobile_api_refresh_token/hc || exit 1
      interval: 60s
      retries: 3
      timeout: 20s
  autoheal:
    image: dokerhub.tnmtm.in:5000/autoheal:latest
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=150
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  file_upload_volumes:
