version: "3.3"
services:
  mobile_api_sendotp:
    image: tnphr/mobileapisendotp
    ports:
      - "9000:5000"
  mobile_api_validateOTP:
    image: tnphr/mobileapivalidateotp
    ports:
      - "9001:5000"
  mobile_api_resendOTP:
    image: tnphr/mobileapiresendotp
    ports:
      - "9002:5000"
  mobile_api_get_facility:
    image: tnphr/mobileapigetfacility
    ports:
      - "9003:5000"
  mobile_api_get_village_street:
    image: tnphr/mobileapigetvillagestreet
    ports:
      - "9004:5000"
  mobile_api_get_block_list:
    image: tnphr/mobileapigetblocklist
    ports:
      - "9005:5000"
  mobile_api_get_clinical_data:
    image: tnphr/mobileapigetclinicaldata
    ports:
      - "9006:5000"
  mobile_api_get_district_list:
    image: tnphr/mobileapigetdistrictlist
    ports:
      - "9007:5000"
  mobile_api_get_family_data:
    image: tnphr/mobileapigetfamilydata
    ports:
      - "9008:5000"
  mobile_api_get_village_list:
    image: tnphr/mobileapigetvillagelist
    ports:
      - "9009:5000"
  mobile_api_get_medical_history:
    image: tnphr/mobileapigetmedicalhistory
    ports:
      - "9010:5000"
  mobile_api_get_screening_data:
    image: tnphr/mobileapigetscreeningdata
    ports:
      - "9011:5000"
  mobile_api_get_search_family_details:
    image: tnphr/mobileapigetsearchfamilydetails
    ports:
      - "9012:5000"
  mobile_api_search:
    image: tnphr/mobileapisearch
    ports:
      - "9013:5000"
  mobile_api_get_family_member_data_V_2_6_0:
    image: tnphr/mobileapigetfamilymemberdata
    ports:
      - "9014:5000"
  mobile_api_add_update_family_detail:
    image: tnphr/mobileapiaddupdatefamilydetail
    ports:
      - "9015:5000"
  phrlocker_api_v1:
    image: vigneshanbu92/phrlocker_api_v1:API1
    ports:
      - "9025:80"
  phrlocker_view_v1:
    image: vigneshanbu92/phrlocker_view_v1:phrlocker-view
    ports:
      - "9026:80"